[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18.x" }

# Production context
[context.production]
  command = "npm run build"

# Deploy Preview context
[context.deploy-preview]
  command = "npm run build"

# Branch Deploy context
[context.branch-deploy]
  command = "npm run build"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = '''
      default-src 'self' https://images.unsplash.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https: blob:;
      font-src 'self' data:;
      connect-src 'self' https:;
      frame-ancestors 'none';
      form-action 'self';
      upgrade-insecure-requests;
    '''
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), vr=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Cache control
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.(?:jpg|jpeg|gif|png|svg|ico)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, no-cache"